apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-jolokia
  namespace: activemq-artemis-broker
data:
  jolokia-access.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <restrict>
    <cors>
    <allow-origin>*://*</allow-origin>
    <strict-checking/>
    </cors>
    </restrict>