apiVersion: apps/v1
kind: Deployment
metadata:
  name: artemis
  namespace: activemq-artemis-broker
  labels:
    app: artemis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artemis
  template:
    metadata:
      labels:
        app: artemis
    spec:
      securityContext:
        runAsUser: 0
      initContainers:
        - name: artemis-init
          image: apache/activemq-artemis:2.30.0
          workingDir: /
          command: [ '/opt/activemq-artemis/bin/artemis', 'create', '--user', 'artemis', '--password', 'password', '--allow-anonymous', 'true', '/etc/activemq-artemis']
          ports:
            - containerPort: 61616
              name: core
            - containerPort: 8161
              name: console
          env:
            - name: ANONYMOUS_LOGIN
              value: "true"
            - name: ACTIVEMQ_NAME
              valueFrom:
                configMapKeyRef:
                  name: artemis-config
                  key: ACTIVEMQ_CONFIG_NAME
            - name: ACTIVEMQ_CONFIG_DEFAULTACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: artemis-config
                  key: ACTIVEMQ_CONFIG_DEFAULTACCOUNT
          volumeMounts:
            - name: broker
              mountPath: /etc/activemq-artemis
      containers:
        - name: artemis
          image: apache/activemq-artemis:2.30.0
          workingDir: /
          command: [ '/etc/activemq-artemis/bin/artemis', 'run']
          ports:
            - containerPort: 61616
              name: tcp
            - containerPort: 8161
              name: admin
          env:
            - name: ANONYMOUS_LOGIN
              value: "true"
            - name: ACTIVEMQ_NAME
              valueFrom:
                configMapKeyRef:
                  name: artemis-config
                  key: ACTIVEMQ_CONFIG_NAME
            - name: ACTIVEMQ_CONFIG_DEFAULTACCOUNT
              valueFrom:
                configMapKeyRef:
                  name: artemis-config
                  key: ACTIVEMQ_CONFIG_DEFAULTACCOUNT
          volumeMounts:
            - name: broker
              mountPath: /etc/activemq-artemis
            - name: certs-keystore
              readOnly: true
              mountPath: /etc/certs/keystore.jks
              subPath: keystore.jks
            - name: certs-truststore
              readOnly: true
              mountPath: /etc/certs/truststore.jks
              subPath: truststore.jks
      volumes:
        - name: broker
          emptyDir:
            sizeLimit: 50Mi
        - name: certs-keystore
          secret:
            secretName: artemis-certs
            items:
              - key: keystore.jks
                path: keystore.jks
        - name: certs-truststore
          secret:
            secretName: artemis-certs
            items:
              - key: truststore.jks
                path: truststore.jks


#        - name: broker-config
#          mountPath: /etc/activemq-artemis/etc/broker.xml
#          subPath: broker.xml
#
#        - name: broker-config
#          configMap:
#            name: broker-config
#            items:
#              - key: broker.xml
#                path: broker.xml

#      volumes:
#        - name: broker
#          persistentVolumeClaim:
#            claimName: artemis-data

#        - name: data
#          persistentVolumeClaim:
#            claimName: artemis-data
#
#
#              - name: data
  #                mountPath: /etc/activemq-artemis/data
