kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artemis-data
  namespace: activemq-artemis-broker
  labels:
    app: artemis
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi