apiVersion: v1
kind: Service
metadata:
  name: artemis-service-external
  namespace: activemq-artemis-broker
  labels:
    app: artemis
spec:
  selector:
    app: artemis
    app.kubernetes.io/name: artemis
  type: NodePort
  ports:
    - protocol: TCP
      name: console
      port: 8161
      targetPort: 8161
      nodePort: 30061